### ISSUE TITLE
rsrcs_rc error

### ISSUE THREAD

**Issue by Rix** [atillaozbiyik/nebula#2]
```
import rsrcs_rc
```
ImportError: No module named 'rsrcs_rc'

Same issue with ui_nebula.py before?

System: Ubuntu 14.04

**Comment by atillaozbiyik** [comment]
fixed. Problem was when generating code python from QtDesigner. Generated code had "import rsrcs_rc" instead of "ui_files.rsrcs_rc"

**Comment by Rix** [comment]
was not fixed, but now fixed with commit : https://github.com/atillaozbiyik/nebula/commit/a4061c4c60ec12b8814d92698052dee04811da14
